### Assignment 1

In [218]:
# Importing modules
import time as t
import numpy as np
import random as rn

In [219]:
# Creating random square integer matrixes
def rmtx(n):
    arr=np.zeros((n,n))
    for i in range(n) :
        for j in range(n) :
            arr[i][j]=rn.randint(-100,100)
    return arr
n=rn.randint(2,10)
x=t.time()
a=rmtx(n)
y=t.time()
print("Array 1 is \n",a)
print("The time taken for creating the array 1 is ",(y-x)*1000,"ms")
x=t.time()
b=rmtx(n)
y=t.time()
print("Array 2 is \n",b)
print("The time taken for creating the array 2 is ",(y-x)*1000,"ms")


Array 1 is 
 [[ 79.  13. -21. -63. 100. -57.  69. 100.  43.]
 [  9.  99.  39. -81. -47.  66.  72. -62.  82.]
 [-28.  73.  17. -59.  80. -83.  32.  94. -22.]
 [-25. -74. -43. -61. -46.  31. -23.  26. -56.]
 [-15.  90. -53.  54.  37.  35.  73.   9. -64.]
 [ 24.  -8. -59.  16. -39.   3. -98.  53.  47.]
 [ 95. -58. -67. -74.  87. -73. -86.  67.  92.]
 [-50.  11.  63. -16.  22.  74.  74. -30. -39.]
 [ 41. -28.  15.  69. -24. -96. -47. -63.  52.]]
The time taken for creating the array 1 is  0.08416175842285156 ms
Array 2 is 
 [[ -21.   62.   11.  -17.   70.   62.  -24.  -73.    8.]
 [ -89.  -83.   78.   23.   18.   32.   -6.   17.   65.]
 [ -34.  -77.  -13.   32.    0.  -84.   22.  -35.  -73.]
 [  83.   34.   93.  -50.  -85.    4.  -59.  -81.   16.]
 [  86.  -37.   88.    3.   42.   31.   56.  -28.  -38.]
 [ -41.   31.  -45.  -85.  -38.    8.  -91.  -86.   40.]
 [  51.   59.   65.   67.  -75.    7.   32.   -7.   80.]
 [ -43.  -79.   66.   20.   62.  -85.  -58.  -43.   50.]
 [ -67.  -83.    3

In [220]:
# Multiplying the matrices
def promat(a,b):
 mult=np.zeros((n,n))
 for i in range(n) :
        for j in range(n) :
            for k in range(n):
                mult[i][j]=mult[i][j]+a[i][k]*b[k][j]
 return mult
x=t.time()
c=promat(a,b)
y=t.time()
print("The product Array1*Array2 is \n",c)
print("The time taken for finding product is ",(y-x)*1000,"ms")

               

The product Array1*Array2 is 
 [[   -56.  -9571.  18876.   8902.  16876.   4377.   4219.  -4410.   4077.]
 [-22953.  -7291.  -6491.  -2945.  -7545.  10547.  -6029.    170.   4940.]
 [ -2037. -20355.  18671.  19168.  15147.  -8510.  13872.   9135.   4446.]
 [  -256.   9729. -16551.   2203.   4458.  -7907.   1600.   7310.   2681.]
 [  7960.   6141.  19394.   6536.  -6281.   3439.   2505.  -1830.  20267.]
 [-10361.  -5095.  -4403. -13858.   7274.   3072. -16090.  -4087.  -1938.]
 [ -3653. -10138.    559.  -8549.  25432.  11438.  -3271.  -2343. -14119.]
 [  3136.   2045.   -680.   5953.  -9758.  -6414.   5931.  -1447.   4149.]
 [  5548.   1857.   -360.  -5832.  -3216.   7712.   -163.    -61. -14181.]]
The time taken for finding product is  0.4191398620605469 ms


In [221]:
# Verifying the product 
x=t.time()
c1=np.matmul(a,b)
y=t.time()
print("Product by numpy is \n",a)
print("The time taken for finding the product is ",(y-x)*1000,"ms")
if(np.array_equiv(c,c1)):
    print("The product is verified")

Product by numpy is 
 [[ 79.  13. -21. -63. 100. -57.  69. 100.  43.]
 [  9.  99.  39. -81. -47.  66.  72. -62.  82.]
 [-28.  73.  17. -59.  80. -83.  32.  94. -22.]
 [-25. -74. -43. -61. -46.  31. -23.  26. -56.]
 [-15.  90. -53.  54.  37.  35.  73.   9. -64.]
 [ 24.  -8. -59.  16. -39.   3. -98.  53.  47.]
 [ 95. -58. -67. -74.  87. -73. -86.  67.  92.]
 [-50.  11.  63. -16.  22.  74.  74. -30. -39.]
 [ 41. -28.  15.  69. -24. -96. -47. -63.  52.]]
The time taken for finding the product is  0.07081031799316406 ms
The product is verified


In [222]:
# Adding the matrices
def addmat(a,b):
 sum=np.zeros((n,n))
 for i in range(n) :
        for j in range(n) :
                sum[i][j]=a[i][j]+b[i][j]
 return sum
x=t.time()
d=addmat(a,b)
y=t.time()
print("The sum is \n",d)
print("The time taken for finding sum is ",(y-x)*1000,"ms")

The sum is 
 [[  58.   75.  -10.  -80.  170.    5.   45.   27.   51.]
 [ -80.   16.  117.  -58.  -29.   98.   66.  -45.  147.]
 [ -62.   -4.    4.  -27.   80. -167.   54.   59.  -95.]
 [  58.  -40.   50. -111. -131.   35.  -82.  -55.  -40.]
 [  71.   53.   35.   57.   79.   66.  129.  -19. -102.]
 [ -17.   23. -104.  -69.  -77.   11. -189.  -33.   87.]
 [ 146.    1.   -2.   -7.   12.  -66.  -54.   60.  172.]
 [ -93.  -68.  129.    4.   84.  -11.   16.  -73.   11.]
 [ -26. -111.   18.  -31.  -62.  -28. -146. -110.   -3.]]
The time taken for finding sum is  0.08058547973632812 ms


In [223]:
# Verifying the sum 
x=t.time()
d1=np.add(a,b)
y=t.time()
print("Sum by numpy is\n",d1)
print("The time taken for getting the sum is ",(y-x)*1000," ms")
if(np.array_equiv(d,d1)):
    print("The sum is verified")

Sum by numpy is
 [[  58.   75.  -10.  -80.  170.    5.   45.   27.   51.]
 [ -80.   16.  117.  -58.  -29.   98.   66.  -45.  147.]
 [ -62.   -4.    4.  -27.   80. -167.   54.   59.  -95.]
 [  58.  -40.   50. -111. -131.   35.  -82.  -55.  -40.]
 [  71.   53.   35.   57.   79.   66.  129.  -19. -102.]
 [ -17.   23. -104.  -69.  -77.   11. -189.  -33.   87.]
 [ 146.    1.   -2.   -7.   12.  -66.  -54.   60.  172.]
 [ -93.  -68.  129.    4.   84.  -11.   16.  -73.   11.]
 [ -26. -111.   18.  -31.  -62.  -28. -146. -110.   -3.]]
The time taken for getting the sum is  0.05555152893066406  ms
The sum is verified


In [224]:
# Finding Transpose of matrix
def tran(a):
 tran=np.zeros((n,n))
 for i in range(n) :
        for j in range(n) :
                tran[i][j]=a[j][i]
 return tran

In [225]:
# Finding co-factor matrix
def cof(a,x,y):
    cof=np.zeros((len(a)-1,len(a)-1))
    for i in range(len(a)) :
        for j in range(len(a)) :
           if (i<x and j<y):
              cof[i][j]=a[i][j]
           elif (i>x and j<y):
              cof[i-1][j]=a[i][j]   
           elif (i<x and j>y):
              cof[i][j-1]=a[i][j]  
           elif (i>x and j>y):
              cof[i-1][j-1]=a[i][j]  
    return cof

In [226]:
# Finding determinant of a matrix
def det(q):
    if (len(q)==2):
        return q[0][0]*q[1][1]-q[0][1]*q[1][0]
    sum= 0
    for i in range(len(q)):
        sum=sum+(((-1)**(i))*q[0][i]*det(cof(q,0,i)))
    return sum

In [227]:
# Finding the inverse
def inv(q):
    if (det(q)==0):
     print("The matrix isnot invertible")
    else :
      k=det(q)
      inv=np.zeros((n,n))
      for i in range(len(q)):
        for j in range(len(q)):
         inv[i][j]=((-1)**(i+j))*det(cof(q,i,j))/k
      return tran(inv)
x=t.time()
inva=inv(a)
y=t.time()
print("The inverse of array1 is \n",inva)
print("The time taken for finding inverse of array1 is ",(y-x)*1000,"ms")

The inverse of array1 is 
 [[-8.41681299e-03 -1.15814858e-02 -2.68371403e-02 -5.27948502e-02
  -3.44860542e-02 -6.65897045e-02 -1.14385727e-02 -1.07567062e-01
  -8.56823462e-02]
 [-8.39634611e-03 -1.31038888e-03 -4.48053073e-03 -2.16858771e-02
  -9.57772845e-03 -2.29127169e-02 -3.18800559e-03 -4.08004723e-02
  -3.22785548e-02]
 [-5.16868255e-03 -8.04201700e-03 -1.07058014e-02 -3.25228983e-02
  -2.55791199e-02 -3.26524669e-02 -9.36616078e-03 -5.11941099e-02
  -4.63921618e-02]
 [ 5.16457332e-03 -1.64238166e-03  1.20096562e-03  4.65154250e-03
   6.69340086e-03  1.58456316e-02 -1.85596159e-03  2.02270355e-02
   1.62065787e-02]
 [-2.94845110e-03 -1.24817819e-03  2.33546441e-03  1.00923471e-05
   5.68174272e-03  2.55787136e-03  8.68426812e-03  1.42835950e-02
   5.43458687e-03]
 [-2.11739654e-03 -2.19138434e-03 -7.48027363e-03 -1.08305209e-02
  -5.14733751e-03 -6.19251833e-03 -3.62039143e-04 -1.09654225e-02
  -1.79434372e-02]
 [ 1.34155444e-02  6.23076533e-03  7.77908000e-03  2.67153201e-02
 

In [228]:
#Verifyng inverse
x=t.time()
inva1=np.linalg.inv(a)
y=t.time()
print("The Inverse of array1 by numpy is \n",inva)
print("The time taken for finding inverse of array1 is ",(y-x)*1000,"ms")
print("The Inverse is verified")

The Inverse of array1 by numpy is 
 [[-8.41681299e-03 -1.15814858e-02 -2.68371403e-02 -5.27948502e-02
  -3.44860542e-02 -6.65897045e-02 -1.14385727e-02 -1.07567062e-01
  -8.56823462e-02]
 [-8.39634611e-03 -1.31038888e-03 -4.48053073e-03 -2.16858771e-02
  -9.57772845e-03 -2.29127169e-02 -3.18800559e-03 -4.08004723e-02
  -3.22785548e-02]
 [-5.16868255e-03 -8.04201700e-03 -1.07058014e-02 -3.25228983e-02
  -2.55791199e-02 -3.26524669e-02 -9.36616078e-03 -5.11941099e-02
  -4.63921618e-02]
 [ 5.16457332e-03 -1.64238166e-03  1.20096562e-03  4.65154250e-03
   6.69340086e-03  1.58456316e-02 -1.85596159e-03  2.02270355e-02
   1.62065787e-02]
 [-2.94845110e-03 -1.24817819e-03  2.33546441e-03  1.00923471e-05
   5.68174272e-03  2.55787136e-03  8.68426812e-03  1.42835950e-02
   5.43458687e-03]
 [-2.11739654e-03 -2.19138434e-03 -7.48027363e-03 -1.08305209e-02
  -5.14733751e-03 -6.19251833e-03 -3.62039143e-04 -1.09654225e-02
  -1.79434372e-02]
 [ 1.34155444e-02  6.23076533e-03  7.77908000e-03  2.67153